### ISSUE TITLE
Getting Error status_code = 403 CRITICAL 403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by ImranBabu** [singer-io/tap-linkedin-ads#6]
ERROR Error status_code = 403
CRITICAL 403 Client Error: Forbidden for url: https://api.linkedin.com/v2/adAccountsV2?q=search&start=0&count=1
Traceback (most recent call last):
  File "d:\anaconda3\envs\airbot\lib\site-packages\tap_linkedin_ads\client.py", line 65, in raise_for_error
    response.raise_for_status()
  File "d:\anaconda3\envs\airbot\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.linkedin.com/v2/adAccountsV2?q=search&start=0&count=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda3\envs\airbot\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\envs\airbot\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\airbot\Scripts\tap-linkedin-ads.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\airbot\lib\site-packages\singer\utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "d:\anaconda3\envs\airbot\lib\site-packages\tap_linkedin_ads\__init__.py", line 34, in main
    with LinkedinClient(access_token=parsed_args.config['access_token'],
  File "d:\anaconda3\envs\airbot\lib\site-packages\tap_linkedin_ads\client.py", line 101, in __enter__
    self.__verified = self.check_access_token()
  File "d:\anaconda3\envs\airbot\lib\site-packages\backoff\_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "d:\anaconda3\envs\airbot\lib\site-packages\tap_linkedin_ads\client.py", line 125, in check_access_token
    raise_for_error(response)
  File "d:\anaconda3\envs\airbot\lib\site-packages\tap_linkedin_ads\client.py", line 85, in raise_for_error
    raise LinkedInError(error)
tap_linkedin_ads.client.LinkedInError: 403 Client Error: Forbidden for url: https://api.linkedin.com/v2/adAccountsV2?q=search&start=0&count=1

**Comment by KaliTHB** [comment]
please select marketing platform tool then u get prmissions and able to work this
